doc: make set up step explicit
valory-xyz/apy-oracle pull request #45
Opened 2023-02-22 14:43 UTC by jmoreira-valory

## Proposed changes

Make set up step explicit in the demo instructions so that it indicates the specific version of Open Autonomy that the service currently supports.

This is done in order to avoid situations where the Open Autonomy framework has been updated with a backwards-incompatible change (and thus the service cannot refer to the "normal" set up instructions).

## Fixes

If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have locally run services that could be impacted and they do not present failures derived from my changes

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-02-22 14:50 UTC, Adamantios requested changes
Please rebase on `chore/bump`.

2023-02-22 15:16 UTC, Adamantios approved these changes

2023-02-22 15:21 UTC, dvilelaf submitted a review, later dismissed

2023-02-22 15:48 UTC, Adamantios commented
Merging my PR and deleting my branch automatically closed this PR @jmoreira-valory . Could you please re-open it?

2023-02-22 16:09 UTC, Adamantios commented
Are you sure you rebased? It seems there are things missing in your file's version compared to the version on `main`.

2023-02-23 10:29 UTC, Adamantios commented on docs/index.md
> +    pipenv install open-autonomy[all]==0.9.0
I do not see a reason to use an empty `Pipfile` and then install the package like this. In general, why use `Pipenv` at all?

2023-02-23 10:38 UTC, jmoreira-valory commented on docs/index.md
> +    pipenv install open-autonomy[all]==0.9.0
IMO I agree we should not instruct to use Pipenv, and not use any Pipenv (or similar) command in the tutorials.

We can *recommend* using Pipenv, and ultimately, it's user's decision if he wants to install the library in a virtual environment or not.

If we want to make this change, we need to make it in the Toolkits, as well as in the main Open Autonomy docs.

2023-02-23 10:52 UTC, Adamantios commented on docs/index.md
> +    pipenv install open-autonomy[all]==0.9.0
Agreed! Sounds too involved, we need to change it in too many places, let's consider that in the future.

2023-02-23 10:54 UTC, Adamantios commented on docs/index.md
> +    pipenv install open-autonomy[all]==0.9.0
Addressed on https://github.com/valory-xyz/apy-oracle/pull/45#discussion_r1115496043.

2023-02-23 10:55 UTC, Adamantios approved these changes

2023-02-23 10:56 UTC, merged

2023-02-23 12:20 UTC, DavidMinarsch commented on docs/index.md
> +    pipenv install open-autonomy[all]==0.9.0
We use Pipenv as otherwise there’s no separation of environments